baseurl: "/"
languageCode: "en-us"
title: "Harish Venkataraman"
theme: "xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "â†©"

permalinks:
  tech: "/tech/:slug/"
  personal: "/personal/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "I blog about different things: deep learning, AI, math, and life in general"
  footer: "&copy; [Harish Venkataraman](http://harishvnkt.com) {Year} | [Github](https://github.com/harish-vnkt) | [Twitter](https://twitter.com/noobharish)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
